<?php

namespace AppBundle\Repository;

/**
 * AuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthRepository extends \Doctrine\ORM\EntityRepository
{
}
